package CIDER::Model::CIDERDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'CIDER::Schema',
    traits => [ qw( SchemaProxy ) ],
);

=head1 NAME

CIDER::Model::CIDERDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<CIDER>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<CIDER::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.41

=head1 AUTHOR

Jason McIntosh

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
